S3:
  bucket: p-idfm-pipeline
  chemins_dossiers:
    bronze: bronze/
    silver: silver/
    gold: gold/
    profiling: profiling/
    quality_reports: quality_reports/
    pipeline_metadata: pipeline_metadata/
    athena_results: athena_results/
  region: eu-west-3

Lambda: 
  fonction: p-idfm-pipeline-fetch-api
  timeout: 300 #en secondes
  memoire_allouee: 256 #à modifier si besoin
  URL_API_NBFER:  https://data.iledefrance-mobilites.fr/api/explore/v2.0/catalog/datasets/histo-validations-reseau-ferre/exports/json #données historiques de traffic
  URL_API_ACCESS: https://data.iledefrance-mobilites.fr/api/explore/v2.0/catalog/datasets/accessibilite-en-gare/exports/json #données de score d'accessibilité en gare
  URL_API_REF: https://data.iledefrance-mobilites.fr/api/explore/v2.0/catalog/datasets/zones-d-arrets/exports/json #données de jointure entre zone ZdA et ZdC pour jointure

Glue:
  nom_du_job: glue-transf-bronzetosilver
  timeout: 10 #en minutes
  memoire: 0.0625 DPU #1/16 DPU, suffisant pour Python Shell
  version: 3.0 #adaptée pour python 3.9

Athena: 
  nom: athena-idfm
  chemin_output: athena_results/

Pipeline: 
  environnement: dev
  periode: 2015-2024
  filtre_ZdAtype: #liste d'éléments
    - metroStation
    - railStation
    - liftStation

#rien à stocker pour l'instant : 

#Parameter Store:
  #nom: xxx




